### ISSUE TITLE
EPIC - Centralize dmn files

### ISSUE THREAD

**Issue by gitgabrio** [apache/incubator-kie#6996]
Scope of this epic is to move all the dmn files used for tests into one single place, to
1. avoid duplication of same file
2. avoid having files with same name but different content/semantic

- [x] [Create a single "container" for dmn files](https://github.com/apache/incubator-kie-issues/issues/930)
- [x] [DMN - move significant models to test-resources module](https://github.com/apache/incubator-kie-issues/issues/1023)
- [ ] [Move dmn files from kogito-runtimes - tests to shared module](https://github.com/apache/incubator-kie/issues/6995)

@baldimir @yesamer
