### ISSUE TITLE
EPIC - Set up and document Kogito Quarkus extensions

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie#7001]
Coming from https://github.com/apache/incubator-kie/issues/7002

- Rename the extensions artifacts as agreed in the [spreadsheet](https://docs.google.com/spreadsheets/d/1gsttRcXGtwGQO469EYFDhLxJLEA7Kl3gmioR6XhGhjY/edit#gid=0)
- Verify that call Kogito Quarkus extensions have the right metadata in the `quarkus-extension.yaml` or add it if needed.
- After the release, add all the extensions in the [Quarkus extensions catalog](https://github.com/quarkusio/quarkus-extension-catalog/tree/main/extensions)

Incorporates:
- [x] https://github.com/apache/incubator-kie-issues/issues/917
- [x] https://github.com/apache/incubator-kie-issues/issues/918
- [x] https://github.com/apache/incubator-kie-issues/issues/932
- [x] https://github.com/apache/incubator-kie-issues/issues/933
- [x] https://github.com/apache/incubator-kie-issues/issues/934
- [x] https://github.com/apache/incubator-kie-issues/issues/935
- [x] https://github.com/apache/incubator-kie-issues/issues/1045
- [x] https://github.com/apache/incubator-kie-kogito-images/issues/1749
- [ ] https://github.com/apache/incubator-kie/issues/6999
- [ ] https://github.com/apache/incubator-kie/issues/6998

**Comment by pefernan** [comment]
More insights: https://kie.zulipchat.com/#narrow/stream/232677-drools/topic/Quarkus.20extension/near/419812623
